### ISSUE TITLE
Make tests runnable, and run them automatically with Travis CI

### ISSUE THREAD

**Issue by mreid-moz** [mozilla/jupyter-notebook-gist#36]
@agjwong mentioned that you can make the tests work by running from a specific directory - we should make sure we can run the tests from the correct directory, then setup Travis CI to automatically run the tests when new code is pushed.

**Comment by agjwong** [comment]
@mreid-moz is there a specific account i should use for Travis CI or just my personal github?

**Comment by mreid-moz** [comment]
If you want to test your travis.yml file, the easiest way is probably to fork this repo and use your personal github account.  Once we merge it back in, I'll have to set up Travis for the repository.  I don't have admin access anymore after we moved to the 'mozilla' org, so I'll have to bug someone to get it back :)

**Comment by mreid-moz** [comment]
Ok, I _think_ the main repo is setup to work with travis, but we'll know for sure when we add the travis config file.

**Comment by mreid-moz** [comment]
Resolved by @agjwong in #38
