### ISSUE TITLE
Oauth client secret not recognized

### ISSUE THREAD

**Issue by elfnor** [mozilla/jupyter-notebook-gist#44]
I followed the install instructions, but get the following error in the console. I get four new buttons in the toolbar and can download public gists but not upload etc.

I'm running Anaconda 64 bit, python 3.5
`Python 3.5.1 |Anaconda 2.4.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]`

```
[W 17:31:19.327 NotebookApp] Config option `oauth_client_secret` not recognized
by `NotebookApp`.  Did you mean `cookie_secret`?
[W 17:31:19.329 NotebookApp] Config option `oauth_client_id` not recognized by `
NotebookApp`.
[W 17:31:19.330 NotebookApp] Unrecognized JSON config file version, assuming ver
sion 1
[I 17:31:21.060 NotebookApp] Serving notebooks from local directory: C:\Users\e.
howick
[I 17:31:21.061 NotebookApp] 0 active kernels
[I 17:31:21.061 NotebookApp] The Jupyter Notebook is running at: http://localhos
t:8888/
[I 17:31:21.062 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
```

**Comment by yeah568** [comment]
Do you have a ```jupyter_notebook_config.json``` file in your .jupyter directory? I found it freaks out a bit if you don't have it.

**Comment by mreid-moz** [comment]
I've seen this warning as well, though even with the warning I'm able to create a gist as expected. Have you set up an "Authorized Application" on github as described in the README?

Do you see any further errors in the Jupyter log when you try to create a gist?

**Comment by elfnor** [comment]
OK, I've been away from the relevant computer for the last week.

I have the same `juypter_notebook_config.json` as @yeah568.

When I open a notebook and try to create a gist using the toolbar button `save notebook as gist` I get a 404 page on github and the following line in the console 

`[I 15:42:46.372 NotebookApp] Saving file at /notes_to_self.ipynb`

Is there a log file somewhere or a way to create one?

The url of the 404 page 
`https://github.com/login/oauth/authorize?client_id=elfnor&scope=gist&redirect_uri=http://localhost:8888/create_gist?nb_path=......=` where I've removed a long string of alphanumeric.

**Comment by mreid-moz** [comment]
I don't think a personal access token will work with this code. You need to set up an OAuth Application. Here's a screenshot of the setup for the one I created for testing/development (with the Client ID and Secret _hopefully_ snipped 😄)
<img width="600" alt="example_oauth_app" src="https://cloud.githubusercontent.com/assets/969479/14916551/add90efc-0df0-11e6-8cfb-277754a48b66.png">

**Comment by agjwong** [comment]
After setting things up as mreid-moz suggested, please check your `.jupyter` directory and confirm that you have **three** things inside -jupyter-notebook-config.py, nbconfig (a folder) and **jupyter-notebook-config.json**.  The json file is the one most likely absent from your folder.  If this is the case, go into the nbconfig folder - if the file is there, move it into the .jupyter folder and it should work.  The `Config option `oauth_client_secret` not recognized
by `NotebookApp`.  Did you mean `cookie_secret`?` error should persist but at least you can use the extension until we look into the cause of these messages.

**Comment by elfnor** [comment]
I've followed @mreid-moz  instructions and set up a OAuth Application and it all apears to work. I still get the 
```
'Config option `oauth_client_secret` not recognized
by `NotebookApp`.  Did you mean `cookie_secret`?
```
error. But I can up load a notebook to a gist. 

My `.jupyter` folder has 
folders:
```
nbconfig
custom 
```
files:
```
jupyter-notebook-config.py
jupyter-notebook-config.json.
migrated
```

Thanks very much for the help, this should be a great way to store all those snippets and examples that need acess from different places.

**Comment by agjwong** [comment]
Is the `jupyter-notebook-config.json` file in `nbconfig `or in `.jupyter`?

If it is inside `nbconfig`, please move it into the `.jupyter` folder.  The message should remain but you should not 404 anymore.

**Comment by agjwong** [comment]
Great to hear it is working!

Is the `jupyter-notebook-config.json` file in `.jupyter` or `nbconfig`?

**Comment by elfnor** [comment]
@agjwong  `jupyter-notebook-config.json` is in `.jupyter`

**Comment by mreid-moz** [comment]
@elfnor Great! Glad you're able to create gists!

@agjwong tracked down the warning message to the `notebookapp.py` file in Jupyter that complains a little when you add custom configuration fields to it. It shouldn't affect the functionality, though.

**Comment by mreid-moz** [comment]
I've added a link to the above screenshot to the README, hopefully that'll clarify things in the future. Thanks again @elfnor!
