### ISSUE TITLE
Editing config file on server load results in json syntax errors

### ISSUE THREAD

**Issue by sammyaboum** [mozilla/jupyter-notebook-gist#56]
Hello. I am trying to use nbextensions but every time I open it there is a reload button. I found a fix but each time I have to edit a file and execute a piece of code. I was discussing it with someone on [/jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions) and he said I should raise an issue here. Here is the link to the previous issue where you can see the different issues  I was facing [link_issue_1192](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/issues/1192)

**Comment by jcb91** [comment]
probably related to https://github.com/mozilla/jupyter-notebook-gist/issues/53
